import { readdir, readFile, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const root = process.cwd();
const outputPath = path.join(root, 'src/generated/projectStats.ts');

const ignoredDirectories = new Set([
    '.git',
    '.wrangler',
    'node_modules',
    'dist',
    'build',
    'coverage',
]);

const ignoredFileNames = new Set([
    'package-lock.json',
    'pnpm-lock.yaml',
    'yarn.lock',
    'npm-debug.log',
]);

const generatedFiles = new Set([
    normalizePath(path.relative(root, outputPath)),
]);

const codeExtensions = new Set(['.ts', '.tsx', '.sql']);
const scriptExtensions = new Set(['.js', '.mjs', '.ts']);
const configFiles = new Set([
    'package.json',
    'tsconfig.json',
    'wrangler.toml',
]);

function normalizePath(value) {
    return value.split(path.sep).join('/');
}

function shouldSkipDirectory(name) {
    return ignoredDirectories.has(name) || name.endsWith('.cache');
}

function shouldCountFile(relativePath) {
    const normalized = normalizePath(relativePath);
    const baseName = path.basename(normalized);
    if (ignoredFileNames.has(baseName)) return false;
    if (generatedFiles.has(normalized)) return false;
    if (configFiles.has(normalized)) return true;

    const ext = path.extname(normalized);
    if (normalized.startsWith('src/')) return codeExtensions.has(ext);
    if (normalized.startsWith('scripts/')) return scriptExtensions.has(ext);
    if (normalized.startsWith('migrations/')) return ext === '.sql';
    return false;
}

async function listProjectFiles(directory) {
    const entries = await readdir(directory, { withFileTypes: true });
    const files = [];
    for (const entry of entries) {
        if (entry.isDirectory() && shouldSkipDirectory(entry.name)) continue;
        const fullPath = path.join(directory, entry.name);
        if (entry.isDirectory()) {
            files.push(...await listProjectFiles(fullPath));
            continue;
        }
        if (!entry.isFile()) continue;
        const relativePath = path.relative(root, fullPath);
        if (shouldCountFile(relativePath)) files.push(fullPath);
    }
    return files;
}

function countLines(content) {
    if (content.length === 0) return 0;
    return content.split(/\r\n|\r|\n/).length;
}

const files = await listProjectFiles(root);
let codeLines = 0;
for (const file of files) {
    codeLines += countLines(await readFile(file, 'utf8'));
}

const label = new Intl.NumberFormat('en-US').format(codeLines);
const generated = `// This file is generated by scripts/generateProjectStats.mjs. Do not edit manually.
export const PROJECT_CODE_LINES = ${codeLines};
export const PROJECT_CODE_LINES_LABEL = "${label}";
`;

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(outputPath, generated);
console.log(`Generated src/generated/projectStats.ts with ${label} project code lines.`);
